### ISSUE TITLE
Destination sign indices incompatible with Comet-IV

### ISSUE THREAD

**Issue by aorozco623** [YoRyan/open-nec#20]
Hello again,

So, I noticed two issues regarding destination boards on the NJT Comets.

The first one I noticed with all comets is that when I select a destination, the Comet V matches the one I chose, but the ones on the Comet IVs do not.

I also noticed when I play with Comet Vs leading with an ALP 45 DP in the back, the destination selection tool keeps popping up, even when I don't use the shortcut to pull it up.

Hopefully these issues can be resolved soon.

Thank you!

**Comment by YoRyan** [comment]
Yes, you're right about the signs not matching up. I'll look into it.

Regarding the destination selector appearing randomly, have you tried the latest stable release? There was a fix for that. I've just ran NJCL scenario 7, "New York Night Shift," and also did not encounter this issue.

**Comment by aorozco623** [comment]
I don't think I have, but I will now.

Thank you!

**Comment by aorozco623** [comment]
The new update has helped the latter issue, thank you!

**Comment by YoRyan** [comment]
Glad to hear it!
