### ISSUE TITLE
No sound in game

### ISSUE THREAD

**Issue by sub442** [YoRyan/open-nec#9]
I've just installed version 2.0 of openNEC, however it appears my game sounds are silent.

**Comment by YoRyan** [comment]
Is it just a certain loco, or all of them? Are you able to drive normally otherwise, just without the sound?

I'm very surprised you're having sound problems because this mod doesn't touch any of the sound blueprints.

**Comment by sub442** [comment]
Hey so it seems to be all of my locomotives, and the in game menu sound isn't playing either which is weird. I can drive them normally just without sound

**Comment by YoRyan** [comment]
Definitely weird. There is nothing in the mod that should touch your menu music, nor your other, non-NEC content.

I have to suspect that something else is going on here. Perhaps the game is simply muted in the Windows volume mixer? Maybe try validating your files in Steam?

**Comment by sub442** [comment]
Yeah I just figured out it was avast giving me the problem, just uninstalled it and evrything seems to work now. Weird haha, but thanks for the help! Keep up the amazing work on this project!

**Comment by YoRyan** [comment]
Glad to hear you found a solution!
